tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/formula-analytics"
tap "homebrew/services"
tap "homebrew/test-bot"
brew "asdf"
brew "automake"
brew "cmake"
brew "exa"
brew "fd"
brew "gh"
brew "git"
brew "gnupg"
brew "neovim"
brew "openssl"
brew "readline"
brew "hub"
brew "jq"
brew "jsonlint"
brew "mas"
brew "memcached", restart_service: true
brew "neo4j"
brew "pinentry"
brew "postgresql", restart_service: true
brew "ripgrep"
brew "shellcheck"
brew "ssh-copy-id"
brew "wget"
brew "xsv"
cask "alfred"
cask "appcleaner"
cask "discord"
cask "docker"
cask "dropbox"
cask "firefox"
cask "firefox-developer-edition"
cask "fork"
cask "google-chrome"
cask "google-cloud-sdk"
cask "java8"
cask "keepingyouawake"
cask "licecap"
cask "muzzle"
cask "neo4j"
cask "1password"
cask "1pasword-cli"
cask "postico"
cask "private-internet-access"
cask "visual-studio-code"
mas "DaisyDisk", id: 411643860
mas "Dash", id: 458034879
mas "Evernote", id: 406056744
mas "Slack", id: 803453959
mas "Spectrum", id: 518156125
mas "Xcode", id: 497799835
