#!/bin/bash
# Run by Strap after script/setup on macOS

set -eo pipefail

cd "$(dirname "$0")/.." || exit

# Configure Terminal.app to not close window on shell exit
/usr/libexec/PlistBuddy ~/Library/Preferences/com.apple.Terminal.plist -c \
  "Set 'Window Settings':Basic:shellExitAction 1" || true
defaults read com.apple.Terminal >/dev/null 2>&1 || true

# Add GitHub credentials if missing
if command -v "gh" >/dev/null && ! gh auth token &>/dev/null; then
  gh auth login --git-protocol https --hostname github.com --web
fi

# Enable Touch ID for sudo
bin/touchid-enable-pam-sudo --quiet || true

# Use ZSH as my default Shell
if [ "${SHELL}" != "/bin/zsh" ]; then
  sudo chsh -s /bin/zsh "${USER}"
fi

# Ensure auto-update is always enabled
if [ "$(defaults read /Library/Preferences/com.apple.commerce.plist AutoUpdate)" != "1" ]; then
  sudo defaults write /Library/Preferences/com.apple.commerce.plist AutoUpdate 1
fi

# macOS appearance: Auto (Light by day, Dark by night)
defaults write -g AppleInterfaceStyleSwitchesAutomatically -bool true

# Dock aligned to the bottom
defaults write com.apple.dock orientation -string bottom
killall Dock || true

# Prefer tabs when opening documents: Always
defaults write -g AppleWindowTabbingMode -string Always
